name: Meu primeiro workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  boas-vindas:
    runs-on: ubuntu-latest
    steps:
      - name: Cumprimentar a turma
        run: echo "Olá, Pessoal!"
      - name: Listar arquivos
        run: ls -la